##
## Pterodactyl Container Variables
#
## DO NOT OVERWRITE WITH PTERODACTYL ".env" CONFIGURATIONS!
## This configuration may look like it has pterodactyl
## variables, and it does, however this config also contains
## variables to initialize/setup the containers. If you are migrating
## or planning to use /data/pterodactyl.conf for all your variables,
## remove anything after "panel variables" stated.
##

##
## Container Variables
##

## Location of SSL Certificate and key
## Point to a valid certificate to enable https.

### This has to be changed later while configuring lets encrypt for your panel
SSL_CERT="/etc/certs/cert.pem"
SSL_CERT_KEY="/etc/certs/cert.key"

##
## Panel Variables
## These variables can be used within pterodactyl.conf (.env when symlinked
## into the docker webroot). These variables are also set via pterodactyl:env
## and pterodactyl:mail.
##

## This is the base url for your pterodactyl panel. This should be pointing to your domain
- APP_URL=http://localhost/
+ APP_URL=http://<domain>/

APP_ENV=production
APP_DEBUG=false # DO NOT ENABLE!!! This toggles the ability to enable debug messages on errors.

## Use this to define your timezone. For German users that would be: Europe/Berlin
- APP_TIMEZONE=America/New_York
+ APP_TIMEZONE=Europe/Berlin

APP_ENVIRONMENT_ONLY=true

## Cache/Session Settings
## You dont need to change any of these
CACHE_DRIVER=redis
SESSION_DRIVER=redis
QUEUE_CONNECTION=redis

## Redis Settings
REDIS_HOST=cache
REDIS_PORT=6379

## MySQL Settings
## While youre not using the mysql instance from outside the docker stack you dont need to modify this variables
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=pterodactyl
DB_USERNAME=ptero
DB_PASSWORD=pterodbpass

## Mail Settings
## Use this to configure your email settings.
MAIL_DRIVER=mail
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=tls
MAIL_FROM=no-reply@example.com
